---
name: Check

on:
  pull_request:
    branches: ["master"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: gevhaz/word-warden@v1.0.0
        with:
          preprocessing_script: .github/scripts/preprocess-for-spellchecking.sed
          files: "**/!(tempora-maxime|lorem|id-modi|LICENSE).md"

  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: false

  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.102.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          set -x
          pwd
          ls
          hugo \
            --minify \
            --baseURL grotius.example.com \
            --theme hugo-theme-notrack/ \
            --themesDir ../../ \
            --printUnusedTemplates \
        working-directory: ./exampleSite
